# Basic Version of TD-MPC2 Config for Stacking Tasks
defaults:
- override hydra/launcher: submitit_local
task: stack-3-bricks
obs: state
episodic: false
checkpoint: ???
eval_episodes: 5
eval_freq: 10000
steps: 500000
batch_size: 128
reward_coef: 0.1
value_coef: 0.1
termination_coef: 1
consistency_coef: 30
rho: 0.8
lr: 0.0001
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.98
discount_max: 0.995
buffer_size: 1000000
exp_name: default
data_dir: ???
mpc: true
iterations: 6
num_samples: 1024
num_elites: 128
num_pi_trajs: 24
horizon: 7
min_std: 0.1
max_std: 1.5
temperature: 0.3
log_std_min: -10
log_std_max: 2
entropy_coef: 0.0005
num_bins: 101
vmin: -10
vmax: 10
model_size: 5
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8
wandb_project: V3-TD-MPC2-Stacking-Optimized
wandb_entity: hiroki-kimiwada-
wandb_silent: false
enable_wandb: true
save_csv: true
compile: true
save_video: true
save_agent: true
seed: 1
episode_length: 1200
seed_steps: 6000
action_dim: 9
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
bin_size: ???
